#!/usr/bin/env python3
"""
PyFlink Streaming Consumer: Endpoint Security Logs to Iceberg

This PyFlink streaming job reads endpoint security events from Kafka
and writes them to an Iceberg table on S3 for ultra-low latency analytics.

Architecture:
- Source: Kafka topic "endpoint_logs"
- Processing: PyFlink Table API
- Sink: Iceberg table on S3 with Glue Catalog
- Format: Iceberg (optimized for analytics)

Deployment: Amazon Managed Service for Apache Flink (Amazon MSF)
"""

import os
import json
import logging
import pyflink
from pyflink.table import EnvironmentSettings, TableEnvironment

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Location of the configuration file when running on Managed Flink.
# NOTE: this is not the file included in the project, but a file generated by Managed Flink, based on the
# application configuration.
APPLICATION_PROPERTIES_FILE_PATH = "/etc/flink/application_properties.json"

# Set the environment variable IS_LOCAL=true in your local development environment,
# or in the run profile of your IDE: the application relies on this variable to run in local mode (as a standalone
# Python application, as opposed to running in a Flink cluster).
# Differently from Java Flink, PyFlink cannot automatically detect when running in local mode
is_local = (
    True if os.environ.get("IS_LOCAL") else False
)

# Utility method, extracting properties from the runtime configuration file
def get_application_properties():
    # When running locally (IS_LOCAL=true), always use local application_properties.json
    if is_local:
        local_properties_file = "application_properties.json"
        if os.path.isfile(local_properties_file):
            print('Running in local mode. Loading configuration from "{}"'.format(local_properties_file))
            with open(local_properties_file, "r") as file:
                contents = file.read()
                properties = json.loads(contents)
                return properties
        else:
            print('ERROR: IS_LOCAL=true but local file "{}" not found'.format(local_properties_file))
            return None
    
    # When running on Amazon MSF, use the runtime configuration file
    if os.path.isfile(APPLICATION_PROPERTIES_FILE_PATH):
        with open(APPLICATION_PROPERTIES_FILE_PATH, "r") as file:
            contents = file.read()
            properties = json.loads(contents)
            return properties
    else:
        print('A file at "{}" was not found'.format(APPLICATION_PROPERTIES_FILE_PATH))
        return None

# Utility method, extracting a property from a property group
def property_map(props, property_group_id):
    if props is None:
        return None
    for prop in props:
        if prop["PropertyGroupId"] == property_group_id:
            return prop["PropertyMap"]
    return None

def create_table_environment() -> TableEnvironment:
    """
    Create PyFlink Table Environment with streaming configuration.
    
    Returns:
        Configured TableEnvironment for streaming
    """
    logger.info("Creating PyFlink Table Environment...")
    
    # Create streaming environment
    env_settings = EnvironmentSettings.in_streaming_mode()
    table_env = TableEnvironment.create(env_settings)
    
    # Enable checkpointing for fault tolerance
    table_env.get_config().get_configuration().set_string(
        "execution.checkpointing.interval", "60s"
        )
    table_env.get_config().get_configuration().set_string(
        "execution.checkpointing.interval", "1 min"
    )

    ##############################################
    # Set special configuration for local mode
    ##############################################
    
    if is_local:
        # Load the configuration from the json file included in the project
        APPLICATION_PROPERTIES_FILE_PATH = "application_properties.json"
    
        # Point to the fat-jar generated by Maven, containing all jar dependencies (e.g. connectors)
        CURRENT_DIR = os.path.dirname(os.path.realpath(__file__))
        table_env.get_config().get_configuration().set_string(
            "pipeline.jars",
            # For local development (only): use the fat-jar containing all dependencies, generated by `mvn package`
            # located in the target/ subdirectory
            "file:///" + CURRENT_DIR + "/target/pyflink-dependencies.jar",
        )
    
        # Show the PyFlink home directory and the directory where logs will be written, when running locally
        print("PyFlink home: " + os.path.dirname(os.path.abspath(pyflink.__file__)))
        print("Logging directory: " + os.path.dirname(os.path.abspath(pyflink.__file__)) + '/log')

    logger.info("✅ Table Environment created")
    return table_env


def create_kafka_source_table(table_env: TableEnvironment):
    """
    Create Kafka source table for consuming endpoint security events.
    
    Args:
        table_env: PyFlink TableEnvironment
    """
    logger.info(f"Creating Kafka source table for topic: {kafka_topic_name}")
    
    # Create Kafka source table with JSON format
    # Note: Column names must match the event schema from Lambda producer
    kafka_ddl = f"""
        CREATE TABLE kafka_source (
            event_id STRING,
            customer_id STRING,
            tenant_id STRING,
            device_id STRING,
            device_name STRING,
            device_type STRING,
            event_type STRING,
            event_category STRING,
            severity STRING,
            `timestamp` STRING,
            `user` STRING,
            process_name STRING,
            file_path STRING,
            `action` STRING,
            `result` STRING,
            ip_address STRING,
            os STRING,
            os_version STRING,
            threat_detected BOOLEAN,
            threat_type STRING,
            ingestion_timestamp STRING,
            `source` STRING,
            `version` STRING,
            event_time AS TO_TIMESTAMP(`timestamp`, 'yyyy-MM-dd''T''HH:mm:ss''Z'''),
            WATERMARK FOR event_time AS event_time - INTERVAL '5' SECOND
        ) WITH (
            'connector' = 'kafka',
            'topic' = '{kafka_topic_name}',
            'properties.bootstrap.servers' = '{kafka_bootstrap_servers}',
            'properties.group.id' = '{kafka_consumer_group_id}',
            'scan.startup.mode' = 'earliest-offset',
            'format' = 'json',
            'json.fail-on-missing-field' = 'false',
            'json.ignore-parse-errors' = 'true'
        )
    """
    
    table_env.execute_sql(kafka_ddl)
    logger.info("✅ Kafka source table created")


def create_iceberg_catalog(table_env: TableEnvironment):
    """
    Create Iceberg catalog using AWS Glue Data Catalog.
    
    Args:
        table_env: PyFlink TableEnvironment
    """
    logger.info(f"Creating Iceberg catalog: {iceberg_catalog_name}")
    
    # Create Glue catalog for Iceberg (using working configuration from sample code)
    catalog_ddl = f"""
        CREATE CATALOG {iceberg_catalog_name} WITH (
            'type' = 'iceberg',
            'property-version' = '1',
            'catalog-impl' = 'org.apache.iceberg.aws.glue.GlueCatalog',
            'io-impl' = 'org.apache.iceberg.aws.s3.S3FileIO',
            'warehouse' = '{iceberg_warehouse_path}',
            'aws.region' = '{iceberg_table_region}'
        )
    """
    
    table_env.execute_sql(catalog_ddl)
    logger.info(f"✅ Iceberg catalog '{iceberg_catalog_name}' created")
    
    # Use the catalog
    table_env.use_catalog(iceberg_catalog_name)
    logger.info(f"Using catalog: {iceberg_catalog_name}")


def create_iceberg_database(table_env: TableEnvironment):
    """
    Create Iceberg database if it doesn't exist.
    
    Args:
        table_env: PyFlink TableEnvironment
    """
    logger.info(f"Creating database: {iceberg_database_name}")
    
    database_ddl = f"CREATE DATABASE IF NOT EXISTS {iceberg_database_name}"
    table_env.execute_sql(database_ddl)
    
    # Use the database
    table_env.use_database(iceberg_database_name)
    logger.info(f"✅ Using database: {iceberg_database_name}")


def create_iceberg_sink_table(table_env: TableEnvironment):
    """
    Create Iceberg sink table for storing endpoint security events.
    
    Args:
        table_env: PyFlink TableEnvironment
    """
    logger.info(f"Creating Iceberg sink table: {iceberg_table_name}")
    
    # Create Iceberg table with partitioning
    iceberg_ddl = f"""
        CREATE TABLE IF NOT EXISTS {iceberg_table_name} (
            event_id STRING,
            customer_id STRING,
            tenant_id STRING,
            device_id STRING,
            device_name STRING,
            device_type STRING,
            event_type STRING,
            event_category STRING,
            severity STRING,
            `timestamp` STRING,
            `user` STRING,
            process_name STRING,
            file_path STRING,
            `action` STRING,
            `result` STRING,
            ip_address STRING,
            os STRING,
            os_version STRING,
            threat_detected BOOLEAN,
            threat_type STRING,
            ingestion_timestamp STRING,
            `source` STRING,
            `version` STRING,
            event_time TIMESTAMP(3),
            processing_time TIMESTAMP(3),
            event_year INT,
            event_month INT,
            event_day INT,
            event_hour INT
        ) PARTITIONED BY (event_year, event_month, event_day)
        WITH (
            'format-version' = '2',
            'write.upsert.enabled' = 'false'
        )
    """
    
    table_env.execute_sql(iceberg_ddl)
    logger.info(f"✅ Iceberg sink table '{iceberg_table_name}' created")


def process_and_write_stream(table_env: TableEnvironment):
    """
    Process Kafka stream and write to Iceberg table.
    
    Args:
        table_env: PyFlink TableEnvironment
    """
    logger.info("Starting stream processing...")
    
    # Transform and enrich events
    transform_query = f"""
        INSERT INTO {iceberg_catalog_name}.{iceberg_database_name}.{iceberg_table_name}
        SELECT
            event_id,
            customer_id,
            tenant_id,
            device_id,
            device_name,
            device_type,
            event_type,
            event_category,
            severity,
            `timestamp`,
            `user`,
            process_name,
            file_path,
            `action`,
            `result`,
            ip_address,
            os,
            os_version,
            threat_detected,
            threat_type,
            ingestion_timestamp,
            `source`,
            `version`,
            event_time,
            CURRENT_TIMESTAMP AS processing_time,
            CAST(YEAR(event_time) AS INT) AS event_year,
            CAST(MONTH(event_time) AS INT) AS event_month,
            CAST(DAYOFMONTH(event_time) AS INT) AS event_day,
            CAST(HOUR(event_time) AS INT) AS event_hour
        FROM default_catalog.default_database.kafka_source
    """
    
    # Execute the streaming query
    table_result = table_env.execute_sql(transform_query)
    logger.info("✅ Streaming query started")
    
    return table_result

#####################################
# Load runtime configuration (Global)
#####################################

props = get_application_properties()
consumer_config_0_properties = property_map(props, "consumer.config.0")

# Global configuration variables
iceberg_catalog_name = consumer_config_0_properties["catalog.name"]
iceberg_warehouse_path = consumer_config_0_properties["warehouse.path"]
iceberg_database_name = consumer_config_0_properties["database.name"]
iceberg_table_name = consumer_config_0_properties["table.name"]
iceberg_table_region = consumer_config_0_properties["aws.region"]
kafka_bootstrap_servers = consumer_config_0_properties["kafka.bootstrap.servers"]
kafka_topic_name = consumer_config_0_properties["kafka.topic.name"]
kafka_consumer_group_id = consumer_config_0_properties["kafka.consumer.group.id"]

def main():

    #####################################
    # Default configs
    #####################################

    # Default catalog, database, and input/output tables
    catalog = "default_catalog"
    database = "default_database"
    input_table = f"{catalog}.{database}.kafka_source"

    """
    Main PyFlink streaming pipeline execution.
    """
    logger.info("=" * 70)
    logger.info("PyFlink Endpoint Security Logs Streaming Pipeline")
    logger.info("=" * 70)
    logger.info(f"Kafka Brokers: {kafka_bootstrap_servers}")
    logger.info(f"Kafka Topic: {kafka_topic_name}")
    logger.info(f"Kafka Group: {kafka_consumer_group_id}")
    logger.info(f"Iceberg Catalog: {iceberg_catalog_name}")
    logger.info(f"Database: {iceberg_database_name}")
    logger.info(f"Table: {iceberg_table_name}")
    logger.info(f"Warehouse: {iceberg_warehouse_path}")
    logger.info("=" * 70)
    
    try:
        # Create Table Environment
        table_env = create_table_environment()
        
        # Create Kafka source table
        create_kafka_source_table(table_env)
        
        # Create Iceberg catalog and database
        create_iceberg_catalog(table_env)
        create_iceberg_database(table_env)
        
        # Create Iceberg sink table
        create_iceberg_sink_table(table_env)
        
        # Process and write stream
        table_result = process_and_write_stream(table_env)
        
        logger.info("🚀 Pipeline running. Waiting for data...")
        logger.info("Press Ctrl+C to stop (or let Amazon MSF manage lifecycle)")
        
        # Wait for job completion (in Amazon MSF, this runs indefinitely)
        table_result.wait()
        
    except KeyboardInterrupt:
        logger.info("Pipeline stopped by user")
    except Exception as e:
        logger.error(f"Pipeline error: {e}", exc_info=True)
        raise


if __name__ == "__main__":
    main()
