#!/usr/bin/env python3
"""
PyFlink Streaming Consumer with Real-Time Aggregations

This PyFlink streaming job demonstrates three windowing strategies:
1. Tumbling Windows - Fixed time periods for compliance reporting
2. Sliding Windows - Overlapping windows for real-time alerting
3. Session Windows - Activity-based windows for attack campaign detection

Architecture:
- Source: Kafka topic "endpoint_logs"
- Processing: PyFlink Table API with multiple windowing strategies
- Sinks: 
  * Raw events → endpoint_data_flink
  * Tumbling aggregations → threat_summary_tumbling_*
  * Sliding aggregations → threat_summary_sliding
  * Session aggregations → threat_sessions

Deployment: Amazon Managed Service for Apache Flink (Amazon MSF)
"""

import os
import logging
import json
from typing import List
from pyflink.table import EnvironmentSettings, TableEnvironment
import pyflink

# Import modular components
from aggregation_config import AggregationConfig
from table_creators import (
    create_kafka_source_table,
    create_iceberg_catalog,
    create_iceberg_database,
    create_raw_events_table
)
from aggregation_jobs import (
    create_tumbling_window_aggregations,
    create_sliding_window_aggregation,
    create_session_window_aggregation
)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Location of the configuration file when running on Managed Flink.
# NOTE: this is not the file included in the project, but a file generated by Managed Flink, based on the
# application configuration.
APPLICATION_PROPERTIES_FILE_PATH = "/etc/flink/application_properties.json"

# Set the environment variable IS_LOCAL=true in your local development environment,
# or in the run profile of your IDE: the application relies on this variable to run in local mode (as a standalone
# Python application, as opposed to running in a Flink cluster).
# Differently from Java Flink, PyFlink cannot automatically detect when running in local mode
is_local = (
    True if os.environ.get("IS_LOCAL") else False
)

# Utility method, extracting properties from the runtime configuration file
def get_application_properties():
    # When running locally (IS_LOCAL=true), always use local application_properties.json
    if is_local:
        local_properties_file = "application_properties.json"
        if os.path.isfile(local_properties_file):
            print('Running in local mode. Loading configuration from "{}"'.format(local_properties_file))
            with open(local_properties_file, "r") as file:
                contents = file.read()
                properties = json.loads(contents)
                return properties
        else:
            print('ERROR: IS_LOCAL=true but local file "{}" not found'.format(local_properties_file))
            return None
    
    # When running on Amazon MSF, use the runtime configuration file
    if os.path.isfile(APPLICATION_PROPERTIES_FILE_PATH):
        with open(APPLICATION_PROPERTIES_FILE_PATH, "r") as file:
            contents = file.read()
            properties = json.loads(contents)
            return properties
    else:
        print('A file at "{}" was not found'.format(APPLICATION_PROPERTIES_FILE_PATH))
        return None

# Utility method, extracting a property from a property group
def property_map(props, property_group_id):
    if props is None:
        return None
    for prop in props:
        if prop["PropertyGroupId"] == property_group_id:
            return prop["PropertyMap"]
    return None

def create_table_environment() -> TableEnvironment:
    """
    Create PyFlink Table Environment with streaming configuration.
    
    Returns:
        Configured TableEnvironment for streaming
    """
    logger.info("Creating PyFlink Table Environment...")
    
    # Create streaming environment
    env_settings = EnvironmentSettings.in_streaming_mode()
    table_env = TableEnvironment.create(env_settings)

    # Enable checkpointing for fault tolerance
    table_env.get_config().get_configuration().set_string(
        "execution.checkpointing.interval", "60s"
        )
    table_env.get_config().get_configuration().set_string(
        "execution.checkpointing.interval", "1 min"
    )

    # Set state TTL for aggregations (clean up old state)
    # 1 hour
    table_env.get_config().get_configuration().set_string(
        "table.exec.state.ttl", "3600000"
        )

    ##############################################
    # Set special configuration for local mode
    ##############################################
    
    if is_local:
        # Load the configuration from the json file included in the project
        APPLICATION_PROPERTIES_FILE_PATH = "application_properties.json"
    
        # Point to the fat-jar generated by Maven, containing all jar dependencies (e.g. connectors)
        CURRENT_DIR = os.path.dirname(os.path.realpath(__file__))
        table_env.get_config().get_configuration().set_string(
            "pipeline.jars",
            # For local development (only): use the fat-jar containing all dependencies, generated by `mvn package`
            # located in the target/ subdirectory
            "file:///" + CURRENT_DIR + "/target/pyflink-dependencies.jar",
        )
    
        # Show the PyFlink home directory and the directory where logs will be written, when running locally
        print("PyFlink home: " + os.path.dirname(os.path.abspath(pyflink.__file__)))
        print("Logging directory: " + os.path.dirname(os.path.abspath(pyflink.__file__)) + '/log')

    logger.info("✅ Table Environment created")
    return table_env


def setup_pipeline(table_env: TableEnvironment, config: AggregationConfig):
    """
    Set up the complete streaming pipeline with all components.
    
    Args:
        table_env: PyFlink TableEnvironment
        config: Aggregation configuration
    """
    logger.info("=" * 70)
    logger.info("Setting up PyFlink Streaming Pipeline")
    logger.info("=" * 70)
    
    # Create Kafka source table
    create_kafka_source_table(
        table_env,
        config.kafka_bootstrap_servers,
        config.kafka_topic,
        config.kafka_group_id
    )
    
    # Create Iceberg catalog and database
    create_iceberg_catalog(
        table_env,
        config.catalog_name,
        config.warehouse_location,
        config.aws_region
    )
    create_iceberg_database(table_env, config.catalog_name, config.database_name)
    
    # Create a StatementSet to execute all INSERT queries concurrently
    statement_set = table_env.create_statement_set()
    
    # Create raw events table and add ingestion query
    if raw_events:
        logger.info("📝 Setting up raw events ingestion...")
        create_raw_events_table(
            table_env,
            config.catalog_name,
            config.database_name,
            config.table_name
        )
        add_raw_events_ingestion(statement_set, config)
    
    # Create tumbling window aggregations
    if tumbling_windows:
        logger.info("📊 Setting up tumbling window aggregations...")
        create_tumbling_window_aggregations(
            table_env,
            statement_set,
            config,
            window_minutes=tumbling_window_minutes
        )
    
    # Create sliding window aggregation
    if sliding_windows:
        logger.info("🔄 Setting up sliding window aggregation...")
        create_sliding_window_aggregation(
            table_env,
            statement_set,
            config,
            window_size_minutes=sliding_window_size_minutes,
            slide_interval_minutes=sliding_window_slide_minutes
        )
    
    # Create session window aggregation
    if session_windows:
        logger.info("🎯 Setting up session window aggregation...")
        create_session_window_aggregation(
            table_env,
            statement_set,
            config,
            session_gap_minutes=session_gap_minutes
        )
    
    logger.info("=" * 70)
    logger.info("✅ Pipeline setup complete - executing all queries...")
    logger.info("=" * 70)
    
    # Execute all INSERT queries concurrently
    table_result = statement_set.execute()
    logger.info("🚀 All streaming queries started successfully!")
    
    return table_result


def add_raw_events_ingestion(statement_set, config: AggregationConfig):
    """
    Add raw events ingestion query to the statement set.
    
    Args:
        statement_set: PyFlink StatementSet
        config: Aggregation configuration
    """
    full_table_name = f"{config.catalog_name}.{config.database_name}.{config.table_name}"
    
    query = f"""
        INSERT INTO {full_table_name}
        SELECT
            event_id,
            customer_id,
            tenant_id,
            device_id,
            device_name,
            device_type,
            event_type,
            event_category,
            severity,
            `timestamp`,
            `user`,
            process_name,
            file_path,
            `action`,
            `result`,
            ip_address,
            os,
            os_version,
            threat_detected,
            threat_type,
            ingestion_timestamp,
            `source`,
            `version`,
            event_time,
            CURRENT_TIMESTAMP AS processing_time,
            CAST(YEAR(event_time) AS INT) AS event_year,
            CAST(MONTH(event_time) AS INT) AS event_month,
            CAST(DAYOFMONTH(event_time) AS INT) AS event_day,
            CAST(HOUR(event_time) AS INT) AS event_hour
        FROM default_catalog.default_database.kafka_source
    """
    
    statement_set.add_insert_sql(query)
    logger.info(f"✅ Added raw events ingestion to {full_table_name}")

#####################################
# Load runtime configuration (Global)
#####################################

props = get_application_properties()

# Check if properties were loaded successfully
if props is None:
    raise RuntimeError("Failed to load application properties. Check configuration file.")

consumer_config_0_properties = property_map(props, "consumer.config.0")

# Check if consumer config was found
if consumer_config_0_properties is None:
    raise RuntimeError("Failed to find 'consumer.config.0' property group in configuration.")

# Global configuration variables
iceberg_catalog_name = consumer_config_0_properties["catalog.name"]
iceberg_warehouse_path = consumer_config_0_properties["warehouse.path"]
iceberg_database_name = consumer_config_0_properties["database.name"]
iceberg_table_name = consumer_config_0_properties["table.name"]
iceberg_table_region = consumer_config_0_properties["aws.region"]
kafka_bootstrap_servers = consumer_config_0_properties["kafka.bootstrap.servers"]
kafka_topic_name = consumer_config_0_properties["kafka.topic.name"]
kafka_consumer_group_id = consumer_config_0_properties["kafka.consumer.group.id"]

# Parse boolean flags (they come as strings from config)
raw_events = consumer_config_0_properties.get("enable.raw.events", "false").lower() == "true"
tumbling_windows = consumer_config_0_properties.get("enable.tumbling.windows", "false").lower() == "true"
sliding_windows = consumer_config_0_properties.get("enable.sliding.windows", "false").lower() == "true"
session_windows = consumer_config_0_properties.get("enable.session.windows", "false").lower() == "true"

# Parse window configuration parameters
# Tumbling window durations (comma-separated list of minutes)
tumbling_window_minutes_str = consumer_config_0_properties.get("tumbling.window.minutes", "5,15,30,60")
tumbling_window_minutes = [int(x.strip()) for x in tumbling_window_minutes_str.split(",")]

# Sliding window parameters
sliding_window_size_minutes = int(consumer_config_0_properties.get("sliding.window.size.minutes", "5"))
sliding_window_slide_minutes = int(consumer_config_0_properties.get("sliding.window.slide.minutes", "1"))

# Session window gap
session_gap_minutes = int(consumer_config_0_properties.get("session.gap.minutes", "5"))

def main():
    """
    Main PyFlink streaming pipeline execution.
    """
    logger.info("=" * 70)
    logger.info("PyFlink Endpoint Security Streaming Pipeline")
    logger.info("With Real-Time Aggregations")
    logger.info("=" * 70)
    logger.info(f"Kafka Brokers: {kafka_bootstrap_servers}")
    logger.info(f"Kafka Topic: {kafka_topic_name}")
    logger.info(f"Kafka Group: {kafka_consumer_group_id}")
    logger.info(f"Iceberg Catalog: {iceberg_catalog_name}")
    logger.info(f"Database: {iceberg_database_name}")
    logger.info(f"Table: {iceberg_table_name}")
    logger.info(f"Warehouse: {iceberg_warehouse_path}")
    logger.info("=" * 70)
    logger.info("Enabled Features:")
    logger.info(f"  - Raw Events: {raw_events}")
    logger.info(f"  - Tumbling Windows: {tumbling_windows}")
    if tumbling_windows:
        logger.info(f"    → Window durations: {tumbling_window_minutes} minutes")
    logger.info(f"  - Sliding Windows: {sliding_windows}")
    if sliding_windows:
        logger.info(f"    → Window size: {sliding_window_size_minutes} min, Slide: {sliding_window_slide_minutes} min")
    logger.info(f"  - Session Windows: {session_windows}")
    if session_windows:
        logger.info(f"    → Session gap: {session_gap_minutes} minutes")
    logger.info("=" * 70)
    
    try:
        # Create Table Environment
        table_env = create_table_environment()
        
        # Create configuration
        config = AggregationConfig(
            kafka_bootstrap_servers=kafka_bootstrap_servers,
            kafka_topic=kafka_topic_name,
            kafka_group_id=kafka_consumer_group_id,
            warehouse_location=iceberg_warehouse_path,
            catalog_name=iceberg_catalog_name,
            database_name=iceberg_database_name,
            table_name=iceberg_table_name,
            aws_region=iceberg_table_region
        )
        
        # Setup complete pipeline and execute all queries
        table_result = setup_pipeline(table_env, config)
        
        logger.info("🚀 Pipeline running. Processing events...")
        logger.info("All streaming queries are now running concurrently")
        logger.info("Amazon MSF will manage the lifecycle - job runs until stopped")
        
        # Wait for the job to complete (which is never for streaming)
        # This keeps the main thread alive
        table_result.wait()
        
    except KeyboardInterrupt:
        logger.info("Pipeline stopped by user")
    except Exception as e:
        logger.error(f"Pipeline error: {e}", exc_info=True)
        raise


if __name__ == "__main__":
    main()
